--1. Script Oracle 19c
--Tabla RESULTADOS_EDO
CREATE TABLE RESULTADOS_EDO (

    ID_RESULTADO NUMBER GENERATED ALWAYS AS IDENTITY,
    METODO VARCHAR2(50),
    ECUACION VARCHAR2(200),
    X0 NUMBER,
    Y0 NUMBER,
    H NUMBER,
    ITERACIONES NUMBER,
    RESULTADO_FINAL NUMBER,
    PROCEDIMIENTO CLOB,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_RESULTADOS_EDO
    PRIMARY KEY(ID_RESULTADO)
);

COMMIT;
